-- 코드를 입력하세요
SELECT b.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK b
JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
    GROUP BY BOOK_ID
) s ON s.BOOK_ID = b.BOOK_ID
GROUP BY b.AUTHOR_ID, CATEGORY
ORDER BY b.AUTHOR_ID, CATEGORY DESC
