-- 코드를 작성해주세요
SELECT YEAR, (MAX_SIZE - SIZE_OF_COLONY) YEAR_DEV, ID
FROM(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS m
JOIN ECOLI_DATA e ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY YEAR, YEAR_DEV