-- 코드를 작성해주세요
# SELECT ID, FISH_NAME, LENGTH 
# FROM 
#     (
#     ) AS l
# JOIN FISH_NAME_INFO fn on l.FISH_TYPE = fn.FISH_TYPE
SELECT ID, FISH_NAME, l.LENGTH 
FROM (
    SELECT f.FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO f
    GROUP BY FISH_TYPE
) l
join FISH_INFO f ON f.FISH_TYPE = l.FISH_TYPE AND f.LENGTH = l.LENGTH
JOIN FISH_NAME_INFO fn ON f.FISH_TYPE = fn.FISH_TYPE
