-- 코드를 입력하세요
SELECT t1.CATEGORY, MAX_PRICE, f.PRODUCT_NAME
FROM (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
    FROM FOOD_PRODUCT
    WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'
    GROUP BY CATEGORY
) AS t1
JOIN FOOD_PRODUCT f ON t1.CATEGORY = f.CATEGORY AND t1.MAX_PRICE = f.PRICE
ORDER BY MAX_PRICE DESC